// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using contracts;

#nullable disable

namespace contracts.Migrations
{
    [DbContext(typeof(ExpContext))]
    [Migration("20250523001312_SomeChanges")]
    partial class SomeChanges
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.29")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("contracts.Entities.TestStateMachineState", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uuid");

                    b.Property<string>("CurrentState")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("EndStamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("MachineId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("StartStamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Step1Done")
                        .HasColumnType("boolean");

                    b.Property<bool>("Step2Done")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("ProcessingStates");
                });

            modelBuilder.Entity("contracts.Entities.WorkReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Processed")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TextPayLoad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("WorkerId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("WorkReports");
                });
#pragma warning restore 612, 618
        }
    }
}
